[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-ros.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[source.crates-io]
registry = "https://github.com/rust-lang/crates.io-index"
